// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRoxQ4tx3cwcVsgYIBxTTzCKT9Lv7RBak',
    appId: '1:744541386790:web:158cf27fea3441a18b4ee7',
    messagingSenderId: '744541386790',
    projectId: 'igrow-app-49411',
    authDomain: 'igrow-app-49411.firebaseapp.com',
    databaseURL: 'https://igrow-app-49411-default-rtdb.firebaseio.com',
    storageBucket: 'igrow-app-49411.firebasestorage.app',
    measurementId: 'G-H80CQN2WWN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD372Ypcmtk2gRFSKBFHcal3esARf8SACg',
    appId: '1:744541386790:ios:7f7a1204f739c7318b4ee7',
    messagingSenderId: '744541386790',
    projectId: 'igrow-app-49411',
    databaseURL: 'https://igrow-app-49411-default-rtdb.firebaseio.com',
    storageBucket: 'igrow-app-49411.firebasestorage.app',
    iosBundleId: 'com.example.igrowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD372Ypcmtk2gRFSKBFHcal3esARf8SACg',
    appId: '1:744541386790:ios:7f7a1204f739c7318b4ee7',
    messagingSenderId: '744541386790',
    projectId: 'igrow-app-49411',
    databaseURL: 'https://igrow-app-49411-default-rtdb.firebaseio.com',
    storageBucket: 'igrow-app-49411.firebasestorage.app',
    iosBundleId: 'com.example.igrowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRoxQ4tx3cwcVsgYIBxTTzCKT9Lv7RBak',
    appId: '1:744541386790:web:6c16b33f87b5b88d8b4ee7',
    messagingSenderId: '744541386790',
    projectId: 'igrow-app-49411',
    authDomain: 'igrow-app-49411.firebaseapp.com',
    databaseURL: 'https://igrow-app-49411-default-rtdb.firebaseio.com',
    storageBucket: 'igrow-app-49411.firebasestorage.app',
    measurementId: 'G-0MK1X6R3NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhyrkCsN7YJT5IfuqIi4VIXozkdWR_Diw',
    appId: '1:744541386790:android:6a283a5867a2d8258b4ee7',
    messagingSenderId: '744541386790',
    projectId: 'igrow-app-49411',
    databaseURL: 'https://igrow-app-49411-default-rtdb.firebaseio.com',
    storageBucket: 'igrow-app-49411.firebasestorage.app',
  );

}